version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
volumes:
  pg-data: